"""Licence register (licences.toml), allow-list check, and the ATTRIBUTION.txt text."""

from __future__ import annotations

import tomllib
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from importlib import resources

DEFAULT_ALLOW = ("LicenseRef-PublicDomain-USGov", "CC-BY-4.0")


@dataclass(frozen=True)
class Licence:
    id: str
    name: str
    url: str
    redistributable: bool


class LicenceError(Exception):
    pass


def load_register() -> dict[str, Licence]:
    text = resources.files("camsim_scene").joinpath("licences.toml").read_text(encoding="utf-8")
    return {
        k: Licence(k, v["name"], v.get("url", ""), bool(v["redistributable"])) for k, v in tomllib.loads(text).items()
    }


def check_allowed(licences: Mapping[str, str], allow: Iterable[str]) -> None:
    """`licences`: source id -> licence id. Raises on an unknown licence id or one outside `allow`."""
    reg = load_register()
    allowed = set(allow)
    bad = []
    for sid, lic in sorted(licences.items()):
        if lic not in reg:
            bad.append(f"{sid}: unknown licence {lic!r} (add it to licences.toml)")
        elif lic not in allowed:
            bad.append(
                f"{sid}: licence {lic!r} ({reg[lic].name}) is not on the allow-list; "
                f"pass --allow {lic} only if the package may carry it"
            )
    if bad:
        raise LicenceError("; ".join(bad))


def attribution_text(manifest) -> str:
    reg = load_register()
    lines = [
        f"Scene package {manifest.name}: data sources and attribution",
        "(generated by camsim-scene from manifest.json)",
        "",
    ]
    for s in sorted(manifest.sources, key=lambda s: s.id):
        lic = reg.get(s.licence)
        lic_line = f"  Licence: {lic.name if lic else s.licence}" + (f" ({lic.url})" if lic and lic.url else "")
        lines += [f"{s.dataset} ({s.version})", f"  {s.attribution}", lic_line, f"  Source id: {s.id}", ""]
    return "\n".join(lines)
